### ISSUE TITLE
ECPublicKey is a class here and an interface in libsignal-protocol-java

### ISSUE THREAD

**Issue by mhkhung** [signalapp/libsignal-client#128]
@jack-signal You changed it to a class:
https://github.com/signalapp/libsignal-client/blob/master/java/java/src/main/java/org/whispersystems/libsignal/ecc/ECPublicKey.java

The exact same package/interface exists in another repo:
https://github.com/signalapp/libsignal-protocol-java/blob/master/java/src/main/java/org/whispersystems/libsignal/ecc/ECPublicKey.java

**Comment by jack-signal** [comment]
The API of libsignal-client is not intended to be completely API compatible with libsignal-protocol-java. Our Java wrapper is based on that code, and tried to make only minimal changes but that was purely for the benefit of making the transition of the Android client from the Java to Rust library simpler. It is very likely that over time the libsignal-client Java API will continue to diverge from libsignal-protocol-java (especially as Signal is not itself using libsignal-protocol-java meaning development of that library is effectively stopped).
