### ISSUE TITLE
Deserializations bug of IdentityKeyPair in Swift

### ISSUE THREAD

**Issue by omaarr90** [signalapp/libsignal-client#155]
Swift Struct IdentityKeyPair has a logical error when trying to deserialize IdentityKeyPair from bytes in its init method. the current implementation looks like this: 

```swift
    public init<Bytes: ContiguousBytes>(bytes: Bytes) throws {
        var pubkeyPtr: OpaquePointer?
        var privkeyPtr: OpaquePointer?
        try bytes.withUnsafeBytes {
            try checkError(signal_identitykeypair_deserialize(&pubkeyPtr, &privkeyPtr, $0.baseAddress?.assumingMemoryBound(to: UInt8.self), $0.count))
        }

        publicKey = PublicKey(owned: pubkeyPtr!)
        privateKey = PrivateKey(owned: privkeyPtr!)
    }
```

The order of &privkeyPtr and &pubkeyPtr are mixed up. 

or it could be the order in the `serialize()` method. I think either way will fix it. I tried changing the order in the `init` and it seems to work. I did not try to change the order inside `serialize()` method

you can easily reproduce it by generating a new `IdentityKeyPair` serialize it and then deserialize it and check that public keys do not match as well as private keys.

**Comment by jack-signal** [comment]
Thanks for pointing this out. The C ABI function `signal_identitykeypair_deserialize`  expects the order is private then public but the Swift binding calls it in the reverse order.

cc @jrose-signal

**Comment by jrose-signal** [comment]
I'm not 100% sure we need this as an entry point—the bug went undiscovered so long because the iOS client doesn't (currently) use it. Is there a significant advantage over serializing the public and private keys separately?

**Comment by jack-signal** [comment]
I don't think there is any huge advantage. The X25519 public key is easily re-derived from the private (takes ~.05 ms on my laptop, likely a bit slower on most phones, but fast enough).

The IdentityKeyPair protobuf originates in libsignal-protocol-java. I'm not sure if Android is actually using it either. We may be able to just rip it all out.

**Comment by jrose-signal** [comment]
#127 sounds like even if we don't have a use for the Java entry point, external clients might…though I suppose we could also keep the Java entry point but implement it differently.

**Comment by jrose-signal** [comment]
I ended up just making a PR to fix this specific case because trying to preserve the entrypoint while taking care of format changes sounded like a pain, and then it seemed odd to support this format in Java but not Swift.
