### ISSUE TITLE
CiphertextMessageType::Whisper has wrong numerical value

### ISSUE THREAD

**Issue by nwolber** [signalapp/libsignal-client#242]
CiphertextMessageType::Whisper seems to have the wrong numerical value (https://github.com/signalapp/libsignal-client/blob/master/rust/protocol/src/protocol.rs#L28). The current value is `2` but, according to the Protobuf files, the value should be `1` (e.g. https://github.com/signalapp/Signal-Server/blob/master/service/protobuf/TextSecure.proto#L25).

This results in messages being submitted with type 2 which in turn gets translated to type 2 (KEY_EXCHANGE) in the envelope received at the message destination. The message is then dropped at the destination because no client implements the KEY_EXCHANGE envelope type anymore.

**Comment by jrose-signal** [comment]
CiphertextMessageType doesn't correspond to the envelope message types; it's only used for the type accessor of a CiphertextMessage. The numeric values aren't meaningful other than that they match up with the old libsignal-protocol-java, though with #235 there's an effort planned to keep them in sync with UnidentifiedSenderMessage.Message.Type values going forward.

**Comment by nwolber** [comment]
Thank you for the blazing fast response. 👍
