### ISSUE TITLE
[ Feature ] Rust Library

### ISSUE THREAD

**Issue by princebett** [signalapp/libsignal-client#277]
Hello ! It's rather odd to me that libsignal does not provide a rust library despite being written in rust. 

Is it possible to possible to expose a rust api for people who would like to create desktop/CLI clients  using rust ?
Alternatively do you recommend the use of the now folded libsignal-client-rust ?

Thanks for building Signal !

**Comment by hiqua** [comment]
I think the answer is mostly there: https://github.com/signalapp/libsignal-client/issues/152

**Comment by princebett** [comment]
I see. Thanks for taking the time to respond !

I'll wait for the library to mature. I hope there will be a rust api.

**Comment by Be-ing** [comment]
@princebett if you are trying to write a Signal client in Rust, you probably want the independent [libsignal-service-rs](https://github.com/Michael-F-Bryan/libsignal-service-rs/) library which will [soon use this libsignal-client library](https://github.com/Michael-F-Bryan/libsignal-service-rs/pull/83). If you are trying to create a GUI client, come join us working on Whisperfish. We are [planning](https://gitlab.com/groups/whisperfish/-/epics/5) to decouple it from Sailfish OS and make it run on mobile/desktop Linux. If you are trying to create a CLI client or bot, we are also working on [Presage](https://gitlab.com/whisperfish/presage). Come join us on Matrix at #whisperfish:rubdos.be

**Comment by princebett** [comment]
> @princebett if you are trying to write a Signal client in Rust, you probably want the independent [libsignal-service-rs](https://github.com/Michael-F-Bryan/libsignal-service-rs/) library which will [soon use this libsignal-client library](https://github.com/Michael-F-Bryan/libsignal-service-rs/pull/83). If you are trying to create a GUI client, come join us working on Whisperfish. We are [planning](https://gitlab.com/groups/whisperfish/-/epics/5) to decouple it from Sailfish OS and make it run on mobile/desktop Linux. If you are trying to create a CLI client or bot, we are also working on [Presage](https://gitlab.com/whisperfish/presage). Come join us on Matrix at #whisperfish:rubdos.be

Thanks !! I'll take a look at presage.
