### ISSUE TITLE
Question: Can a ciphertext be sent alongisde a SenderKeyDistributionMessage?

### ISSUE THREAD

**Issue by rlch** [signalapp/libsignal-client#325]
Hey there 😄 

I'm trying to send a ciphertext containing group information (name, avatar, etc...) alongside the SenderKeyDistributionMessage in the initial connection between peers. 

I was wondering if this is possible / if there's a best-practice for sending group metadata on creation. 

My apologies if there's a better place to ask a question of this nature.

**Comment by jrose-signal** [comment]
Yes, there's nothing stopping you from making a Content proto with both an SKDM and something else, and you can see in the early work in the Android codebase that [it's expected](https://github.com/signalapp/Signal-Android/blob/2029ea378f249a70983c1fc3d55b9a63588bc06c/libsignal/service/src/main/java/org/whispersystems/signalservice/api/messages/SignalServiceContent.java#L406-L412).

I'd say a place to ask general questions about Signal clients as a whole (including the layers on top of this library) would be the Development section of https://community.signalusers.org/. These are unofficial forums but some of us visit there, and there are also others working on third-party clients as well.
