### ISSUE TITLE
Feature: Garmin port of Signal client

### ISSUE THREAD

**Issue by MrSimmo** [signalapp/libsignal-client#334]
Not sure if this is possible but would be great if someone was able to port/create a Signal client for Garmin smartwatches such as the Fenix. 

With new watches being supplied with LTE, ie no need to bring a phone along, being able to create and reply to messages natively would be awesome.

**Comment by jrose-signal** [comment]
Thanks for the suggestion! This repository is for the libsignal-client *library,* which is used by the Signal apps; this sort of feature request is better suited for a [support request][] or the [unofficial community forum][].

[support request]: https://support.signal.org/hc/requests/new
[unofficial community forum]: https://community.signalusers.org/
