### ISSUE TITLE
Recommended way to get the android aar?

### ISSUE THREAD

**Issue by archie94** [signalapp/libsignal-client#340]
Hello!

What is the recommended way to get the artifact targeting Android? 

I ran the docker image but even after tests building success I do not see the artifact in the container. Does the docker container cleanup the files on completion?

Thanks for considering this.

**Comment by hiqua** [comment]
Please ask there: https://community.signalusers.org/c/development/android-development/22

**Comment by jrose-signal** [comment]
The output aars are in java/android/build/outputs/aar/, which admittedly is a bit non-discoverable (rather than hunt for it myself I used `find`). Suggestions for a better location? Or should we add that location to the README and call it a day?

**Comment by hilmanfitriana19** [comment]
Hello, I alse tried to build libsignal-client following the readme file by adding rustup and cargo ndk targets but couldn't find the .aar file in any directory (tried to search using the `find` command).

Are there other steps that must be done and not haven't been added to the readme file?

**Comment by archie94** [comment]
> Please ask there: https://community.signalusers.org/c/development/android-development/22

Thank you @hiqua for the heads up.

**Comment by archie94** [comment]
> The output aars are in java/android/build/outputs/aar/, which admittedly is a bit non-discoverable (rather than hunt for it myself I used `find`). Suggestions for a better location? Or should we add that location to the README and call it a day?

Thanks @jrose-signal for your reply. 
At this moment I myself donot have a better location suggestion. And if the location is obvious then it probably doesnot require a special mention on the README.
All over I do think this issue is perhaps due to my lack of depth with gradle build system / docker.

I am going to close this issue for now since I believe the community pointed out by @hiqua should solve most of my doubts.

Thanks again!

**Comment by jrose-signal** [comment]
> Hello, I alse tried to build libsignal-client following the readme file by adding rustup and cargo ndk targets but couldn't find the .aar file in any directory (tried to search using the `find` command).
> 
> Are there other steps that must be done and not haven't been added to the readme file?

The step that actually does the build is `./gradlew test`, but if you did that and it's still not working I'm a bit stymied. We mostly build through the Docker image, though, and that hasn't failed us.
