### ISSUE TITLE
Proxy support

### ISSUE THREAD

**Issue by 3nprob** [signalapp/libsignal-client#345]
As has been brought up in other repos, it would be great with support for routing connections to server through a HTTP or SOCKS proxy, either HTTP or SOCKS5. This is similar to but different from https://github.com/signalapp/Signal-TLS-Proxy

**Comment by jrose-signal** [comment]
libsignal-client doesn't handle any of the talking to the server, just encoding and decoding of messages (often encrypting and decrypting). Each of the individual apps (Signal-Android, Signal-iOS, Signal-Desktop) uses its own platform-provided connection APIs to connect to the server. If you're looking for this as an end-user feature, I suggest [submitting it as a feature request through our support site](https://support.signal.org/hc/en-us/requests/new).
