### ISSUE TITLE
CI: Add Windows build (dll)

### ISSUE THREAD

**Issue by szepeviktor** [signalapp/libsignal-client#355]
Hello!
While reinstalling `AsamK/signal-cli` on Windows 10 I've realized I need `libsignal-client.dll`.
Please consider building this dll file in CI and upload it to GitHub releases.
Thank you!

**Comment by jrose-signal** [comment]
I'm afraid this repository is open source but its primary purpose is to support the three official Signal clients (Android/Java, iOS/Swift, and Desktop/Electron/TypeScript). You'll have to take this up with @AsamK!
