### ISSUE TITLE
Unable to find a specification for `SignalCoreKit` depended upon by `SignalClient`

### ISSUE THREAD

**Issue by dangell7** [signalapp/libsignal-client#363]
Getting this error when install the pod...

`Unable to find a specification for `SignalCoreKit` depended upon by `SignalClient`

Had to add the rust and cargo repos first, maybe I did something wrong?

**Comment by jrose-signal** [comment]
I'm assuming you figured it out, but SignalCoreKit isn't in the general CocoaPods registry; you have to reference it directly as well from https://github.com/signalapp/SignalCoreKit.

**Comment by dangell7** [comment]
No I didn't. I got the local package working then realized I can't use that either as the podspec is in the wrong directory. but that's for the public pod so I understand. 

When you say "reference it directly" you mean add it to the podfile?

**Comment by jrose-signal** [comment]
Yeah, that seems to be the only real option for "I depend on something else packaged as a pod but not part of any registry".

**Comment by dangell7** [comment]
That worked! Thank you so much!
