### ISSUE TITLE
[Awesome FeatureRequest] Pin messages

### ISSUE THREAD

**Issue by Ka55i0peia** [signalapp/libsignal-client#379]
**Use Case** Given a group chat, where users contributes with "much talk"-messages besides informational messages, one like to see the _relevant information_. (E.g. for event planning)

**Solution** (I never saw in messageners) As a group admin I like to mark messages as "pinned" or "information" so, that this messages ...
1. ... can be listed.
2. ... can be seen by people joining later the group

**Nice idea** Place on client side a "like that feature/donate" button, because a new function might motivate some (more) to donate.
 
*In repository [Signal-Server](https://github.com/signalapp/Signal-Server) no issues can be created. I feel like its addressed there better!?*

**Comment by jrose-signal** [comment]
Ah, please direct feature requests to our [Support](https://support.signal.org/hc/requests/new), or join the [unofficial community forum](https://community.signalusers.org/).
