### ISSUE TITLE
Best practice to store IdentityKeyPair, registrationId, PreKeyRecords, SignedPreKeyRecord

### ISSUE THREAD

**Issue by ahmedcs2600** [signalapp/libsignal-client#424]
How do we store  IdentityKeyPair, registration Id, PreKeyRecords, SignedPreKeyRecord permanently in the android app. If the app is uninstalled we don't want to generate new keys. I want to know what is the best practice to store private keys how do we retain the keys after the app is reinstalled.

**Comment by jatin-lakhani** [comment]
+1

**Comment by jrose-signal** [comment]
This kind of question is better suited to the community forums: https://community.signalusers.org/c/development/android-development/22. This library lets you store the information however you want; the Android app chooses to store it as data associated with the app for a variety of reasons.
