### ISSUE TITLE
Add golang implementation/binding

### ISSUE THREAD

**Issue by andig** [signalapp/libsignal-client#439]
It would be great if we could integrate Go programs with Signal. I‘d be happy to become a Signal supporter if we could get Go integration bootstrapped.

**Comment by jrose-signal** [comment]
The bindings that are there today are the ones Signal itself uses in its official apps; I'm afraid we don't have the bandwidth to support anything else. However, I suspect that the C part of the Swift bindings could be used from Go as well, and we'd accept patches that make the library easier to use from Go as long as they don't pose a significant maintenance burden going forwards.
