### ISSUE TITLE
Gradle: Maven plugin deprecated in Gradle 7

### ISSUE THREAD

**Issue by kalihale** [signalapp/libsignal-client#451]
I tried using Gradle 7.4 to build the project and got this error:

![Screenshot from 2022-02-25 18-55-42](https://user-images.githubusercontent.com/56854468/155826258-92109c08-858c-4746-8502-28e7ab17a107.png)
*Could not compile build file, unable to resolve class MavenDeployment*

According to the [Gradle docs](https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin), `maven` is being deprecated in favor of `maven-publish`.

The workaround to this is to use a version of Gradle <7.0, so this is not an urgent issue, but this will likely need to be updated eventually.

**Comment by jrose-signal** [comment]
Yep, thanks. We've been adapting Gradle files from previous projects for a while, now; it's probably time to rewrite it wholesale to use with modern Gradle.

**Comment by jrose-signal** [comment]
Updated to Gradle 7.4 for v0.14.0!
