### ISSUE TITLE
Does this project accept external contributions?

### ISSUE THREAD

**Issue by qhhonx** [signalapp/libsignal-client#80]
It is interesting that rewrites a Instant Message app using Rust in order to unify common logic for some reasons. 

However there is no official roadmap to show its targets or demo project to demonstrate its implemented functionalities for external contributions.

**Comment by jack-signal** [comment]
Once we have a CLA process in place, then yes we will accept external contributions - depending of course on content and assuming it matches the needs of Signal. If it is anything beyond bug fixes, I would suggest first opening an issue to ask if the change would be accepted.

There is no public roadmap only things internal to Signal. We might be able to publish something later but I'm not sure.

As far as a demo goes, this library is used in the official Signal Android client starting in 4.78, which is currently in beta. It replaces the previously used https://github.com/signalapp/libsignal-protocol-java and https://github.com/signalapp/libsignal-metadata-java. 

Right now we are focusing on getting this to the point of being shipped also to the Signal iOS and Desktop clients.
