### ISSUE TITLE
Build for iOS failing

### ISSUE THREAD

**Issue by matthewroche** [signalapp/libsignal-client#84]
I understand that this is an internal project for development, but I am trying to build this for exploration purposes. I am able to get the project to build and operate properly for Swift in macOS, but builds for iOS fail. The Swift documentation state the project is 'set up as a CocoaPod for integration into the Signal iOS client', so I believe iOS builds should succeed. The fact that macOS builds are successful suggests to me this is not a problem with my local Rust set up, but I'm happy to be corrected.

Steps to recreate:
1) Using macOS Big Sur 11.0.1, Xcode 12.2, iOS 14.2.
2) Create a new iOS project using Swift
3) Use `pod init`
4) Add 'pod 'SignalClient', git: 'https://github.com/signalapp/libsignal-client.git' to the pod file
5) `pod install`
6) Try to build for an iOS target.

The error I'm getting is below, and appears to occur during linking whilst compiling get random.

cargo build -p libsignal-ffi --release
   Compiling proc-macro2 v1.0.24
   Compiling syn v1.0.45
   Compiling libc v0.2.79
   Compiling getrandom v0.1.15

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.0.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.1.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.10.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.11.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.12.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.13.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.14.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.15.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.2.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.3.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.4.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.5.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.6.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.7.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.8.rcgu.o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.build_script_build.i1lvbqlc-cgu.9.rcgu.o" "-o" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/build/syn-d54f49b28eca3f98/build_script_build-d54f49b28eca3f98.3bm18redto8u1wev.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/matthewroche/Library/Developer/Xcode/DerivedData/SignalMapsIos-hghgpvfhvntzmveekioanzymzyfq/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/SignalClient.build/DerivedSources/libsignal-ffi/release/deps" "-L" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-ff8f19287472ab25.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-e3d969bfc9686736.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-938ee2d2dbaf220c.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-9bae58925fa3dd0b.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-2ec940c1e1a44ce7.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-a190fa5b69d68147.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-b4be29ebbc3c6d64.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-7798de3537b0376b.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-059af72ed835e91e.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-40807d6e6f06e462.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-ff818040cbe57af0.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-3dc0396c7b6c0532.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-465082706ea1ede1.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-e3cd79f6ad1173fd.rlib" "/Users/matthewroche/.rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-e0d54f11f476b2b7.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: library not found for -lSystem
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

If I go to the folder containing the Pod files in terminal and run `cargo build -p libsignal-ffi --release` then the build is successful, which makes me wonder if this is related to the environment Xcode builds in, but I have been unable to identify a fix after days of searching. I've attached build logs below.

[Build target SignalClient_2020-11-26T14-28-00.txt](https://github.com/signalapp/libsignal-client/files/5603996/Build.target.SignalClient_2020-11-26T14-28-00.txt)

I realise this is unsupported, but would be grateful for any assistance.

**Comment by jrose-signal** [comment]
Hm, nothing jumps out at me yet, but can you check some things?

- What does `xcode-select -p` show? (i.e. is the command-line build actually using the Xcode.app)
- The Xcode build is cross-compiling for iOS with `CARGO_BUILD_TARGET=x86_64-apple-ios`. Does that also succeed for you?

**Comment by matthewroche** [comment]
Thanks for your reply and sorry for the delay.

Quick update: I have successfully built and run the package using cargo-lipo, manually adding the universal libsignal_ffi.a file to 'Link Binary with Libraries', and then manually adding the swift files to my project. Similar to the process described [here](https://mozilla.github.io/firefox-browser-architecture/experiments/2017-09-06-rust-on-ios.html).

To answer your questions:

`xcode-select -p` shows `/Applications/Xcode.app/Contents/Developer`

and

running `cargo build --target=x86_64-apple-ios` from terminal is successful.

I wonder whether this is related to my macOS or Xcode version, but this isn't a theory I'm able to test. I'm happy running the package in the hacky way described above for now, so please close this if you wish. Also happy to help try to debug, but I've reached the end of my knowledge.

**Comment by jrose-signal** [comment]
Y'know, this really looks like the cross-compilation logic is wrong:

> .rustup/toolchains/nightly-2020-11-09-x86_64-apple-darwin/lib/rustlib/**x86_64-apple-darwin**

That second target should be an iOS target, not a Mac one. If you're building in Xcode, what's your Destination? If you're building on the command line, what's your xcodebuild invocation?

**Comment by matthewroche** [comment]
Building in Xcode from a clean project for any iOS simulator destination fails (have tried iPhone 11, iPhone 12 mini and iPod touch 7th gen).

**Comment by jrose-signal** [comment]
:-/ Can you attach the build log for a failing build? (Specifically I want to see the full list of environment variables set for the "Build libsignal-ffi" step, as well as the rest of the Cargo output.)

**Comment by matthewroche** [comment]
Yup. Here you go for the clean project build for iPhone 11.

[Build target SignalClient_2020-12-13T15-26-57.txt](https://github.com/signalapp/libsignal-client/files/5684871/Build.target.SignalClient_2020-12-13T15-26-57.txt)

**Comment by jrose-signal** [comment]
Ahh, these are build tools being built, which is why they're host-side…and so here's my current hypothesis: because of how Xcode passes down SDKs, cargo doesn't have access to the macOS SDK (because we're compiling for iOS), and because you're on Big Sur, the linker is no longer able to use the system libraries to link against.

My work machine isn't currently on Big Sur but I'll start considering workarounds ahead of that.

**Comment by jrose-signal** [comment]
Okay, can you try the branch in #123?

**Comment by matthewroche** [comment]
Working perfectly. Thanks for all your help. Wasted hours trying to debug this, my understanding of the Xcode build system evidently still isn't good enough...

**Comment by jrose-signal** [comment]
Here's a collection of analysis about what Big Sur changed, although more focused towards reverse engineering: https://mjtsai.com/blog/2020/06/26/reverse-engineering-macos-11-0/
